Initial template setup for Vite EtageControl project.
plantquest/leaflet-plugins pull request #5
Opened 2023-11-07 12:07 UTC by Jose-Perigolo

- Setting EtageControl template, renaming variables and files. Initial setup.

2023-11-07 13:10 UTC, rjrodger requested changes

2023-11-07 13:10 UTC, rjrodger commented on EtageControl/dev/index.html
> +    <div><b>Group Select</b></div>
rename to Etage Control

2023-11-07 13:10 UTC, rjrodger commented on EtageControl/vite.config.js
> +        assetFileNames: "group-select.[ext]",
rename

2023-11-07 13:10 UTC, rjrodger commented on EtageControl/vite.config.js
> +      name: 'PlantquestGroupSelect',
rename

2023-11-07 13:35 UTC, Jose-Perigolo commented on EtageControl/dev/index.html
> +    <div><b>Group Select</b></div>
Done.

2023-11-07 13:35 UTC, Jose-Perigolo commented on EtageControl/vite.config.js
> +        assetFileNames: "group-select.[ext]",
Indeed. Done.

2023-11-07 13:35 UTC, Jose-Perigolo commented on EtageControl/vite.config.js
> +      name: 'PlantquestGroupSelect',
Indeed. Done.

2023-11-08 12:21 UTC, rjrodger requested changes

2023-11-08 12:21 UTC, rjrodger commented on EtageControl/src/etage-control.ts
> +    const buildings = [
set using an option

2023-11-09 14:00 UTC, merged